// constants for getting good receipt list
export const GOOD_RECEIPT_LIST_REQUEST = "GOOD_RECEIPT_LIST_REQUEST";
export const GOOD_RECEIPT_LIST_SUCCESS = "GOOD_RECEIPT_LIST_SUCCESS";
export const GOOD_RECEIPT_LIST_FAIL = "GOOD_RECEIPT_LIST_FAIL";

// constants for creating good receipt
export const GOOD_RECEIPT_CREATE_REQUEST = "GOOD_RECEIPT_CREATE_REQUEST";
export const GOOD_RECEIPT_CREATE_SUCCESS = "GOOD_RECEIPT_CREATE_SUCCESS";
export const GOOD_RECEIPT_CREATE_FAIL = "GOOD_RECEIPT_CREATE_FAIL";
