export const DRAFT_ORDER_CREATE_REQUEST = "DRAFT_ORDER_CREATE_REQUEST";
export const DRAFT_ORDER_CREATE_SUCCESS = "DRAFT_ORDER_CREATE_SUCCESS";
export const DRAFT_ORDER_CREATE_FAIL = "DRAFT_ORDER_CREATE_FAIL";

export const DRAFT_ORDER_LIST_REQUEST = "DRAFT_ORDER_LIST_REQUEST";
export const DRAFT_ORDER_LIST_SUCCESS = "DRAFT_ORDER_LIST_SUCCESS";
export const DRAFT_ORDER_LIST_FAIL = "DRAFT_ORDER_LIST_FAIL";

export const DRAFT_ORDER_DELETE_REQUEST = "DRAFT_ORDER_DELETE_REQUEST";
export const DRAFT_ORDER_DELETE_SUCCESS = "DRAFT_ORDER_DELETE_SUCCESS";
export const DRAFT_ORDER_DELETE_FAIL = "DRAFT_ORDER_DELETE_FAIL";

export const DRAFT_ORDER_TO_PENDING_REQUEST = "DRAFT_ORDER_TO_PENDING_REQUEST";
export const DRAFT_ORDER_TO_PENDING_SUCCESS = "DRAFT_ORDER_TO_PENDING_SUCCESS";
export const DRAFT_ORDER_TO_PENDING_FAIL = "DRAFT_ORDER_TO_PENDING_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_TO_APPROVE_REQUEST = "ORDER_TO_APPROVE_REQUEST";
export const ORDER_TO_APPROVE_SUCCESS = "ORDER_TO_APPROVE_SUCCESS";
export const ORDER_TO_APPROVE_FAIL = "ORDER_TO_APPROVE_FAIL";

export const ORDER_LIST_SUPPLIER_REQUEST = "ORDER_TO_SUPPLIER_REQUEST";
export const ORDER_LIST_SUPPLIER_SUCCESS = "ORDER_TO_SUPPLIER_SUCCESS";
export const ORDER_LIST_SUPPLIER_FAIL = "ORDER_LIST_SUPPLIER_FAIL";

export const ORDER_TO_PLACED_REQUEST = "ORDER_TO_PLACED_REQUEST";
export const ORDER_TO_PLACED_SUCCESS = "ORDER_TO_PLACED_SUCCESS";
export const ORDER_TO_PLACED_FAIL = "ORDER_TO_PLACED_FAIL";

export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST";
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS";
export const PLACED_ORDER_FAIL = "PLACED_ORDER_FAIL";

export const STAFF_ORDER_LIST_REQUEST = "STAFF_ORDER_LIST_REQUEST";
export const STAFF_ORDER_LIST_SUCCESS = "STAFF_ORDER_LIST_SUCCESS";
export const SRAFF_ORDER_LIST_FAIL = "SRAFF_ORDER_LIST_FAIL";

export const STAFF_ORDER_APPROVE_REQUEST = "STAFF_ORDER_APPROVE_REQUEST";
export const STAFF_ORDER_APPROVE_SUCCESS = "STAFF_ORDER_APPROVE_SUCCESS";
export const STAFF_ORDER_APPROVE_FAIL = "STAFF_ORDER_APPROVE_FAIL";
