// constants for draft order create
export const DRAFT_ORDER_CREATE_REQUEST = "DRAFT_ORDER_CREATE_REQUEST";
export const DRAFT_ORDER_CREATE_SUCCESS = "DRAFT_ORDER_CREATE_SUCCESS";
export const DRAFT_ORDER_CREATE_FAIL = "DRAFT_ORDER_CREATE_FAIL";

// constants for draft order list
export const DRAFT_ORDER_LIST_REQUEST = "DRAFT_ORDER_LIST_REQUEST";
export const DRAFT_ORDER_LIST_SUCCESS = "DRAFT_ORDER_LIST_SUCCESS";
export const DRAFT_ORDER_LIST_FAIL = "DRAFT_ORDER_LIST_FAIL";

// constants for draft order update
export const DRAFT_ORDER_DELETE_REQUEST = "DRAFT_ORDER_DELETE_REQUEST";
export const DRAFT_ORDER_DELETE_SUCCESS = "DRAFT_ORDER_DELETE_SUCCESS";
export const DRAFT_ORDER_DELETE_FAIL = "DRAFT_ORDER_DELETE_FAIL";

// constants for cinverting draft order to pending
export const DRAFT_ORDER_TO_PENDING_REQUEST = "DRAFT_ORDER_TO_PENDING_REQUEST";
export const DRAFT_ORDER_TO_PENDING_SUCCESS = "DRAFT_ORDER_TO_PENDING_SUCCESS";
export const DRAFT_ORDER_TO_PENDING_FAIL = "DRAFT_ORDER_TO_PENDING_FAIL";

// constatnts for order list
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

// constants for pending order to approver order
export const ORDER_TO_APPROVE_REQUEST = "ORDER_TO_APPROVE_REQUEST";
export const ORDER_TO_APPROVE_SUCCESS = "ORDER_TO_APPROVE_SUCCESS";
export const ORDER_TO_APPROVE_FAIL = "ORDER_TO_APPROVE_FAIL";

// constants for getting selected supplier orders
export const ORDER_LIST_SUPPLIER_REQUEST = "ORDER_TO_SUPPLIER_REQUEST";
export const ORDER_LIST_SUPPLIER_SUCCESS = "ORDER_TO_SUPPLIER_SUCCESS";
export const ORDER_LIST_SUPPLIER_FAIL = "ORDER_LIST_SUPPLIER_FAIL";

// constants for converting approve order to placed order
export const ORDER_TO_PLACED_REQUEST = "ORDER_TO_PLACED_REQUEST";
export const ORDER_TO_PLACED_SUCCESS = "ORDER_TO_PLACED_SUCCESS";
export const ORDER_TO_PLACED_FAIL = "ORDER_TO_PLACED_FAIL";

// constants for getting placed order list
export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST";
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS";
export const PLACED_ORDER_FAIL = "PLACED_ORDER_FAIL";

// constants for staff view of order list by staff
export const STAFF_ORDER_LIST_REQUEST = "STAFF_ORDER_LIST_REQUEST";
export const STAFF_ORDER_LIST_SUCCESS = "STAFF_ORDER_LIST_SUCCESS";
export const SRAFF_ORDER_LIST_FAIL = "SRAFF_ORDER_LIST_FAIL";

// constants for staff aprrove orders by staff
export const STAFF_ORDER_APPROVE_REQUEST = "STAFF_ORDER_APPROVE_REQUEST";
export const STAFF_ORDER_APPROVE_SUCCESS = "STAFF_ORDER_APPROVE_SUCCESS";
export const STAFF_ORDER_APPROVE_FAIL = "STAFF_ORDER_APPROVE_FAIL";
