export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const VIEW_PRODUCT_FOR_SITE_MANAGER_LIST_REQUEST = "VIEW_PRODUCT_FOR_SITE_MANAGER_LIST_REQUEST";
export const VIEW_PRODUCT_FOR_SITE_MANAGER_LIST_SUCCESS = "VIEW_PRODUCT_FOR_SITE_MANAGER_LIST_SUCCESS";
export const VIEW_PRODUCT_FOR_SITE_MANAGER_LIST_FAIL = "VIEW_PRODUCT_FOR_SITE_MANAGER_LIST_FAIL";

export const VIEW_PRODUCT_FOR_STAFF_LIST_REQUEST = "VIEW_PRODUCT_FOR_STAFF_LIST_REQUEST";
export const VIEW_PRODUCT_FOR_STAFF_LIST_SUCCESS = "VIEW_PRODUCT_FOR_STAFF_LIST_SUCCESS";
export const VIEW_PRODUCT_FOR_STAFF_LIST_FAIL = "VIEW_PRODUCT_FOR_STAFF_LIST_FAIL";
