export const SITE_MANGER_LOGIN_REQUEST = "SITE_MANGER_LOGIN_REQUEST";
export const SITE_MANGER_LOGIN_SUCCESS = "SITE_MANGER_LOGIN_SUCCESS";
export const SITE_MANGER_LOGIN_FAIL = "SITE_MANGER_LOGIN_FAIL";
export const SITE_MANGER_LOGOUT = "SITE_MANGER_LOGOUT";
