export const SITE_MANGER_LOGIN_REQUEST = "SITE_MANGER_LOGIN_REQUEST";
export const SITE_MANGER_LOGIN_SUCCESS = "SITE_MANGER_LOGIN_SUCCESS";
export const SITE_MANGER_LOGIN_FAIL = "SITE_MANGER_LOGIN_FAIL";
export const SITE_MANGER_LOGOUT = "SITE_MANGER_LOGOUT";

export const SITE_MANAGER_REGISTER_REQUEST = "SITE_MANAGER_REGISTER_REQUEST";
export const SITE_MANAGER_REGISTER_SUCCESS = "SITE_MANAGER_REGISTER_SUCCESS";
export const SITE_MANAGER_REGISTER_FAIL = "SITE_MANAGER_REGISTER_FAIL";
