export const STAFF_LOGIN_REQUEST = "STAFF_LOGIN_REQUEST";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAIL = "STAFF_LOGIN_FAIL";
export const STAFF_LOGOUT = "STAFF_LOGOUT";

export const STAFF_REGISTER_REQUEST = "STAFF_REGISTER_REQUEST";
export const STAFF_REGISTER_SUCCESS = "STAFF_REGISTER_SUCCESS";
export const STAFF_REGISTER_FAIL = "STAFF_REGISTER_FAIL";
