export const STAFF_LOGIN_REQUEST = "STAFF_LOGIN_REQUEST";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAIL = "STAFF_LOGIN_FAIL";
export const STAFF_LOGOUT = "STAFF_LOGOUT";
