//supplier constants to connect actions and reducers
export const SUPPLIER_LOGIN_REQUEST = "SUPPLIER_LOGIN_REQUEST";
export const SUPPLIER_LOGIN_SUCCESS = "SUPPLIER_LOGIN_SUCCESS";
export const SUPPLIER_LOGIN_FAIL = "SUPPLIER_LOGIN_FAIL";
export const SUPPLIER_LOGOUT = "SUPPLIER_LOGOUT";

export const SUPPLIER_REGISTER_REQUEST = "SUPPLIER_REGISTER_REQUEST";
export const SUPPLIER_REGISTER_SUCCESS = "SUPPLIER_REGISTER_SUCCESS";
export const SUPPLIER_REGISTER_FAIL = "SUPPLIER_REGISTER_FAIL";
